Сделал домашку по Java Collections
rubikkubika/hh-school-2022-java-collections-stream pull request #1
Opened 2022-12-07 13:53 UTC by rubikkubika

2022-12-08 11:18 UTC, genroelgvozo requested changes

2022-12-08 11:18 UTC, genroelgvozo commented on src/main/java/tasks/Task1.java
> +Сложность сортировки O(n * log n)
а надо за O(n) )
слово сортировка тут может запутать, по факту никакой сортировки и не надо, надо просто расположить в правильном порядке (и некоторая идея в твоем коде уже есть, но зайди с другой стороны)

2022-12-08 11:18 UTC, genroelgvozo commented on src/main/java/tasks/Task3.java
> +                    .thenComparing(Person::getCreatedAt))
выглядит все ок, но код иногда может падать... Подумай почему)

2022-12-08 11:18 UTC, genroelgvozo commented on src/main/java/tasks/Task5.java
> +            .map(person ->personConverter.convert(person,personAreaIds.get(person.getId())))
все окей, но отсутствующие пробелы в некоторых местах это жестко)

2022-12-08 11:18 UTC, genroelgvozo commented on src/main/java/tasks/Task6.java
> +                    .map(area -> person.getFirstName() + " - "+ areaList.get(area -1).getName()))
так, вижу что на такое проходит юнит тест и посыпаю голову пеплом. Но сделано вообще не то)
в personAreaIds находятся айдишки ареек, а на их номера в коллекции (которая может быть не листом вообще)

2022-12-08 11:18 UTC, genroelgvozo commented on src/main/java/tasks/Task7.java
> +            .flatMap(company -> company.getVacancies().stream().map(Vacancy::getTitle))
работает, но по стилю лучше выносить map из flatMap как минимум
ну а на вкус я вообще еще бы разбил так:
.map(Company::getVacancies)
.flatMap(Collection::stream)
.map(Vacancy::getTitle)
когда меньше стрелочек и скобочек по мне так лучше читается, но это на вкус

2022-12-08 11:18 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  3. Удалил remove, добавил skip  return
вот вопрос тут - чем плохо изначально?

2022-12-08 11:18 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    1.Заменил второй Second Name на Middle Name
и остался еще некоторый бажок в функции если secondName==null, то будет пробел в начале лишний

И в целом это тримом можно пофиксить, но суть в том как раз, что когда мы погружаемся до уровня "как сделать" и пишем все эти технические ифчики, стрингбилдеры и т.д. в таких прикладных простых методах, очень просто совершить ошибку. А вот если писать код в стиле "что сделать" не вдаваясь в детали, то будет проще.. хмм, кажется у стримов есть Collectors.joining() =)

2022-12-08 11:18 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +            .collect(Collectors.toMap(Person::getId,Person::getFirstName));
твой код иногда будет падать, а мой не падал

2022-12-08 11:18 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +            .anyMatch(new HashSet<>(persons2)::contains);
это перфекто)

2022-12-08 11:18 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    2.Переписал Stream api с помощью count
только в этом случае сразу в return лучше писать, зачем здесь переменная

ну и а что было не так изначально?

2022-12-08 11:51 UTC, genroelgvozo requested changes

2022-12-08 11:51 UTC, genroelgvozo commented on src/main/java/tasks/Task2.java
> +            .sorted(Comparator.comparing(Person::getCreatedAt))
И тут тест упал, и не зря (глазами не увидел что не так)

2022-12-08 13:38 UTC, rubikkubika commented on src/main/java/tasks/Task1.java
> +Сложность сортировки O(n * log n)
Убрал сортировку.
Сразу создаем Map и записываем туда Person и порядок
Потом в стриме через .map() конвертируем id в Person

2022-12-08 13:39 UTC, rubikkubika commented on src/main/java/tasks/Task2.java
> +            .sorted(Comparator.comparing(Person::getCreatedAt))
Поправил. Сначала фильтруем потом ограничиваем.
Странно в идее почемуто тест проходил

2022-12-08 13:40 UTC, rubikkubika commented on src/main/java/tasks/Task3.java
> +                    .thenComparing(Person::getCreatedAt))
Падает когда Имя или фамилия могут быть null
Добавил использование Comparator.nullFirst

2022-12-08 13:40 UTC, rubikkubika commented on src/main/java/tasks/Task5.java
> +            .map(person ->personConverter.convert(person,personAreaIds.get(person.getId())))
Поправил.
Пробелы сбились, так как я понимаю настроены кастомные отступы.
При применении ctrl+alt+l они ломаются

2022-12-08 13:40 UTC, rubikkubika commented on src/main/java/tasks/Task6.java
> +                    .map(area -> person.getFirstName() + " - "+ areaList.get(area -1).getName()))
Вставил второй тест, но видимо он не запустится,т.к. сравнени с мейном идет
Сделал через использование Map  c  Id и Area, а не через List

2022-12-08 13:40 UTC, rubikkubika commented on src/main/java/tasks/Task7.java
> +            .flatMap(company -> company.getVacancies().stream().map(Vacancy::getTitle))
Поправил

2022-12-08 13:41 UTC, rubikkubika commented on src/main/java/tasks/Task8.java
> +  3. Удалил remove, добавил skip  return
Удаление элемента меняет исходный List
Более удобная запись, т.к. не надо писать проверку на пустой список?

2022-12-08 13:41 UTC, rubikkubika commented on src/main/java/tasks/Task8.java
> +    1.Заменил второй Second Name на Middle Name
Переписал.
Добавил проверку на пустую строку  и null
Добавил Collectors.joining()

2022-12-08 13:41 UTC, rubikkubika commented on src/main/java/tasks/Task8.java
> +            .collect(Collectors.toMap(Person::getId,Person::getFirstName));
Падать будет при попытке добавить дубликаты
Добавил mergeFunction для дубликатов

2022-12-08 13:41 UTC, rubikkubika commented on src/main/java/tasks/Task8.java
> +    2.Переписал Stream api с помощью count
Когда писал, думал что просто более понятный код.

По теме нашел статью https://ru.stackoverflow.com/questions/625153/%D0%97%D0%B0%D1%85%D0%B2%D0%B0%D1%82-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B9-%D0%B2-%D0%BB%D1%8F%D0%BC%D0%B1%D0%B4%D0%B0-%D0%B2%D1%8B%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8

Получается, что использование через count() подходит для многопоточного программирования.
А твой метод  - это возможность обмануть компилятор в плане ограничения на effectively final значение переменной

2022-12-12 05:21 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  3. Удалил remove, добавил skip  return
ну да, в целом менять входной лист плохо, никто не ожидает от функции с названием getчто-то

2022-12-12 05:21 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  3. Удалил remove, добавил skip  return
ну и List.of() вообще бы упал)

2022-12-12 05:22 UTC, genroelgvozo commented on src/main/java/tasks/Task5.java
> +            .map(person ->personConverter.convert(person,personAreaIds.get(person.getId())))
так можно же на этот проект настроить такие же) (кстати в хх 2-2-4, а не 4-4-8 как по умолчанию в идее)

2022-12-12 05:25 UTC, genroelgvozo approved these changes

2022-12-12 05:25 UTC, genroelgvozo commented on src/main/java/tasks/Task1.java
> +    Map<Integer,Person> orderPersonMap=persons.stream()
все ок, правда название не удачное, в мапе никакого ордер и быть не может
это просто idPersonMap или иное подходящее название

порядок то как раз в personIds содержится

2022-12-12 06:37 UTC, merged